version: 2
jobs: 
  test:
    docker:
      - image: circleci/python:3.6.4
    steps: 
      - checkout
      - run:
          name: unit tests
          command: |
            ls
            sudo pip install -r requirements.txt
            python tests.py
      - store_test_results:
          path: test.db
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test