version: 2
jobs: 
  test:
    docker:
      - image: circleci/python:3.6.4
    steps: 
      - checkout
      - run:
          name: unit tests
          command: |
            ls
            sudo pip install -r requirements.txt
            python tests.py
      - store_test_results:
          path: test.db
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps: 
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/ca-project:$CIRCLE_SHA1
      - run: sudo apt install zip -y
      - run: zip -r artifact.zip .
      - store_artifacts:
        path: ./artifacts.zip
        destination: build-artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-test:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - attach_workspace:
          at: .
      - run: sh deploymentscript.sh
  deploy-product:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: sh deploymentscript2.sh
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - dockerize:
          requires:
            - test
      - deploy-test:
          requires:
            - dockerize
          filters:
            branches:
              ignore:
                - master
      - deploy-product:
          filters:
            branches:
              only: master